class RecipeFood {
  String name;
  String type;
  String description;
  List<String> ingredients;
  List<String> step;
  String imagePoster;
  List<String> imageUrls;

  RecipeFood({
    required this.name,
    required this.type,
    required this.description,
    required this.ingredients,
    required this.step,
    required this.imagePoster,
    required this.imageUrls,
  });
}

var recipeFoodList = [
  RecipeFood(
    name: 'Pempek Adaan',
    type: 'Appetizer',
    description:
    'Pempek merupakan makanan khas Palembang yang memiliki banyak sekali variannya. Salah satunya adalah Pempek Adaan atau juga dikenal dengan nama Pempek Bulat karena bentuknya yang bulat.',
    ingredients: [
      'BAHAN ADONAN :',
      '1 kg ikan tenggiri giling',
      '500 gr es serut / air es',
      '4 sdm garam',
      '5 sdm gula pasir',
      '4 sdm kaldu jamur / penyedap',
      '6 siung bawang putih, blender halus',
      '2 butir putih telur',
      '800 gr sagu',
      '100 gr bawang merah, cincang kasar',
      '4 batang daun bawang, iris',
      '50 ml minyak panas',
      '150 ml santan',
      'BAHAN CUKO :',
      '500 gr gula merah batok',
      '60 gr cabai rawit hijau',
      '12 siung bawang putih',
      '2 sdm ebi kering, rendam air hangat',
      '2 sdm cuka',
      '30 gr asam jawa, rendam air hangat',
      '2 sdt garam',
      '2 sdm gula pasir',
      '750 ml air',
    ],
    step: [
      '1. Untuk kuah cuko, didihkan air, gula dan asam jawa, masak hingga mendidih',
      '2. Blender ebi, cabai rawit hijau, bawang putih dan sedikit air hingga halus',
      '3. Saring kuah cuko kemudian masukkan bumbu halus ke dalam kuah cuko. Tambahkan garam, gula pasir dan cuka, masak hingga mendidih dan matang',
      '4. Siram daun bawang dengan minyak panas, aduk rata',
      '5. Untuk adonan, masukkan ikan tenggiri, garam, kaldu jamur dan gula pasir ke dalam mixer, aduk hingga lengket',
      '6. Masukkan es serut, mixer hingga menyatu kemudian masukkan bawang putih, putih telur dan tepung sagu, aduk hingga merata',
      '7. Masukkan bawang merah, daun bawang dan santan, aduk rata',
      '8. Bentuk bulat adonan dengan scoop ice cream yang sudah di celupkan ke dalam minyak lalu goreng hingga kecokelatan di api sedang, tiriskan',
      '9. Untuk tekstur lebih krispi, potong-potong pempek yang sudah matang lalu goreng kembali hingga kering, tiriskan',
      '10. Pempek siap disajikan',
    ],
    imagePoster: 'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/01/2024/02/21/1n01bsib-2611838643.png',
    imageUrls: [
      'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/01/2024/02/21/1n01bsib-2611838643.png'
    ],
  ), RecipeFood(
    name: 'Siomay Ayam Udang',
    type: 'Appetizer',
    description:
    'Siomay Ayam Udangggg',
    ingredients: [
      'BAHAN MARINASI BILAS :',
      '350 gr paha ayam filet',
      '100  gr udang kupas',
      '1 sdt garam',
      '2 sdt gula pasir',
      '½ sdt baking powder',
      'Bahan lainnya:',
      'bawang putih parut + 1 sdm air',
      'jahe parut + 1 sdm air',
      '1 butir putih telur',
      '50 ml air es',
      '2 sdt saus tiram',
      '2 sdt minyak wijen',
      '½ sdm kecap asin',
      '1-2 sdm minyak',
      '½ sdm garam',
      '1 sdm gula pasir',
      '1 sdt kaldu jamur / penyedap',
      '¼ sdt merica',
      '5 sdm tepung tapioka',
      'kulit siomay untuk membungkus',
      'wortel, potong kotak kecil',
    ],
    step: [
      '1. Marinasi ayam dan udang dengan baking powder, garam dan gula pasir, aduk rata. Diamkan selama 15-30 menit',
      '2. Bilas ayam dan udang hingga bersih lalu keringkan',
      '3. Campurkan air ke dalam jahe dan bawang putih yang sudah di parut',
      '4. Masukkan sebagian ayam ke dalam food processor beserta garam, gula pasir, kaldu jamur dan merica, haluskan hingga lengket',
      '5. Masukkan air jahe, air bawang putih, putih telur, minyak, kecap asin, saus tiram, minyak wijen dan tepung tapioka',
      '6. Potong sisa ayam dan udang lalu masukkan ke dalam food processor, haluskan sesaat',
      '7. Pindahkan ke dalam mangkuk, tambahkan air es, aduk rata',
      '8. Bentuk adonan dengan kulit siomay. Kukus selama 15 menit',
      '9. Siomay hongkong siap disajikan',
    ],
    imagePoster: 'https://media-cdn.tripadvisor.com/media/photo-s/17/31/47/7c/udang.jpg',
    imageUrls: [
      'https://media-cdn.tripadvisor.com/media/photo-s/17/31/47/7c/udang.jpg'
    ],
  ),

  RecipeFood(
    name: 'Opor Ayam Kuning',
    type: 'Main Course',
    description:
    'Opor ayam bumbu kuning bisa kamu santap dengan nasi, ketupat, ataupun lontong. Cocok juga dipadukan dengan lauk lainnya, seperti sambal goreng ati atau kering kentang',
    ingredients: [
      'BAHAN :',
      '800 gr ayam negeri, potong',
      '½ buah jeruk nipis',
      '2 sdt garam',
      'BAHAN BUMBU ALUS :',
      '5 siung bawang putih',
      '5 siung bawang merah',
      '3 butir kemiri, sangrai',
      '5 cm kunyit, bakar',
      '¾ sdt lada putih butir',
      '1 sdt ketumbar',
      '2 sdm minyak',
      '50 ml air',
      'BAHAN AROMATIK :',
      '2 batang serai',
      '2 lembar daun salam',
      '3 lembar daun jeruk',
      '3 cm lengkuas',
      'BAHAN LAINNYA :',
      '200 ml santan',
      '600 ml air',
      '20 gr gula merah',
      '½ sdt garam',
      '1 sdt kaldu ayam bubuk',
      '½ sdt penyedap',
      '5 siung bawang merah',
      'PELENGKAP :',
      'nasi putih',
      'lontong',
      'ketupat',
    ],
    step: [
      '1. Marinasi ayam dengan perasan jeruk nipis dan garam, aduk rata. Diamkan selama 15-30 menit',
      '2. Potong bawang putih, bawang merah dan geprek kemiri kemudian masukkan ke dalam blender',
      '3. Masukkan kunyit, ketumbar, lada putih butir, minyak dan air, blender hingga halus',
      '4. Iris bawang merah, tumis hingga wangi kemudian masukkan bumbu halus, tumis di api sedang hingga mengeluarkan minyak',
      '5. Geprek serai dan lengkuas lalu masukkan ke dalam tumisan berserta daun salam dan daun jeruk, tumis hingga wangi',
      '6. Masukkan ayam, tumis sesaat lalu masukkan air dan santan, aduk rata',
      '7. Masukkan garam, kaldu ayam bubuk, penyedap dan gula merah, masak hingga matang di api kecil',
      '8. Opor ayam kuning siap disajikan',
    ],
    imagePoster: 'https://asset-a.grid.id/crop/0x0:0x0/945x630/photo/2024/04/02/dhhfjpg-20240402024032.jpg',
    imageUrls: [
      'https://asset-a.grid.id/crop/0x0:0x0/945x630/photo/2024/04/02/dhhfjpg-20240402024032.jpg'
    ],
  ),
  RecipeFood(
    name: 'Sup Iga Kuah Bening',
    type: 'Main Course',
    description:
        'Iga sapi disukai lantaran dagingnya yang gurih namun masih berserat. Salah satu olahan iga sapi yang perlu kamu coba adalah sop iga sapi bening. ',
    ingredients: [
      'BAHAN :',
      '1,5 kg iga sapi',
      '1 sdt garam',
      '3 lembar daun salam',
      '1 liter air',
      '4 cm jahe',
      'BAHAN LAINNYA :',
      '5 siung bawang putih',
      '5 siung bawang merah',
      '3 cm jahe',
      '½ sdt lada putih',
      '¾ butir pala',
      '4 butir cengkih',
      '3 butir kapulaga',
      '3,3 liter air',
      '1 ½ sdm garam',
      '1 sdm kaldu jamur / penyedap',
      '1 sdt gula pasir',
      '1 sdt kaldu sapi bubuk',
      '1 batang daun bawang, potong',
      '5 batang seledri, potong',
      '1 buah tomat merah',
      'PELENGKAP:',
      '2 buah kentang',
      '3 buah wortel',
      '2 sdm bawang goreng',
      'Tomat merah',
      'Sambal rawit hijau',
      'Jeruk nipis',
    ],
    step: [
    '1. Didihkan air, masukan iga sapi, jahe, daun salam, dan garam kedalam presto. Masak di api besar selama 10 menit, lalu kecilkan api masak selama 20 menit. Diamkan daging dalam presto tanpa membuka tutup',
    '2. Geprek bawang putih, jahe, dan bawang merah. Potong besar kentang dan wortel.',
    '3. Didihkan kembali air di panci yang berbeda.',
    '4. Masukan iga, bawang putih, jahe, bawang merah dan tomat, cengkih, pala, kapulaga, merica, garam, kaldu jamur, gula pasir, dan kaldu sapi bubuk.',
    '5. Masukan kentang dan wortel. Masak selama 20 menit',
    '6. Masukkan daun bawang, seledri dan bawang merah goreng ke dalam sup. Masak selama 1-2 menit',
    '7. Sup iga sapi siap disajikan',
    ],
    imagePoster: 'https://i.ytimg.com/vi/wpO2qn_D_nY/sddefault.jpg?v=64be2162',
    imageUrls: [
      'https://i.ytimg.com/vi/wpO2qn_D_nY/sddefault.jpg?v=64be2162',
    ],
  ),
  RecipeFood(
    name: 'Es Teler Cake Dessert Box',
    type: 'Dessert',
    description:
        'Buat Buka Puasa Bisa',
    ingredients: [
      'BAHAN CHIFFON CAKE :',
      '6 butir kuning telur',
      '65 ml minyak',
      '100 ml jus pandan',
      '30 ml santan Kara',
      '½ sdt garam',
      '130 gr tepung terigu protein rendah',
      '6 gr baking powder',
      '½ sdt perisa pandan',
      '6 butir putih telur',
      '100 gr gula pasir',
      '½ sdt cream of tartar / 1 sdt perasan lemon',
      'BAHAN SANTAN CREAM :',
      '300 ml whipping cream',
      '100 ml santan Kara',
      '50 gr kental manis',
      '¼ sdt garam',
      'BAHAN AVOCADO CREAM :',
      '350 gr alpukat',
      '60 gr kental manis',
      'PELENGKAP :',
      'nangka, potong kotak kecil',
      'kelapa muda, potong memanjang',
    ],
    step: [
      '1. Di dalam mangkuk campurkan kuning telur, jus pandan, minyak, santan, garam, tepung terigu dan baking powder sambil disaring, aduk dengan ballon whisk',
      '2. Masukkan perisa pandan, aduk rata',
      '3. Di dalam mangkuk lain masukkan putih telur, gula pasir dan cream of tartar, kocok dengan mixer hingga membentuk paruh burung',
      '4. Masukkan adonan putih telur ke dalam adonan kuning telur secara bertahap, aduk perlahan',
      '5. Tuang ke dalam loyang yang sudah di alasi baking paper. Ketuk-ketuk loyang dan panggang di suhu 150 derajat selama 30 menit',
      '6. Masukkan alpukat dan kental manis ke dalam blender, haluskan hingga menyatu dan masukkan ke dalam plastik segitiga',
      '7. Di dalam mangkuk, campurkan whipping cream, santan dan garam, kocok hingga set lalu masukkan kental manis, kocok sesaat hingga menyatu',
      '8. Masukkan santan cream ke dalam plastik segitiga dan simpan di dalam kulkas',
      '9. Potong cake sesuai ukuran dessert box yang akan digunakan',
      '10. Susun chiffon cake, santan cream, nangka, kelapa muda, santan cream, avocado cream, chiffon cake, santan cream, avocado cream, santan cream, nangka dan kelapa muda. Simpan di dalam kulkas sebelum disajikan',
      '11. Es teller dessert box siap disajikan',
    ],
    imagePoster: 'https://i.ytimg.com/vi/y5TZvqppzG8/maxresdefault.jpg',
    imageUrls: [
      'https://i.ytimg.com/vi/y5TZvqppzG8/maxresdefault.jpg',
    ],
  ),
  RecipeFood(
    name: 'ES KOPYOR',
    type: 'Dessert',
    description:
    'Es Kopyor adalah salah satu makanan penutup yang paling populer di Indonesia. Brownies kukus yang memiliki tekstur yang lembut dan rasa yang manis ini sangat cocok untuk dinikmati bersama keluarga.',
    ingredients: [
      'Bahan jeli:',
      '1 bungkus jeli bubuk polos',
      '1 bungkus agar-agar bubuk polos',
      '½ sdt garam',
      '600 ml santan instan',
      '300 ml air kelapa / air',
      'Bahan gula pandan:',
      '2 lembar daun pandan',
      '150 gr gula pasir',
      '150 ml air',
      'Pelengkap:',
      'susu evaporasi',
      'es batu',
      'sirup cocopandan',
      'nata de coco',
      'selasih',

    ],
    step: [
      '1. Di dalam panci masukkan jeli bubuk, agar bubuk, garam, santan dan air kelapa, aduk rata. Nyalakan api dan masak hingga mendidih sambil di aduk',
      '2. Masukkan ke dalam cetakan. Dinginkan hingga set',
      '3. Di dalam panci, masukkan gula pasir, air dan daun pandan, masak hingga mendidih',
      '4. Keruk jeli kopyor dengan alat kerukan kelapa atau dengan sendok',
      '5. Siapkan gelas, susun es batu, 2-3 sdm sirup cocopandan, nata de coco, kopyor, selasih, es batu, 2-3 sdm sirup gula, kopyor dan susu evaporasi',
      '6. Es kopyor imitasi siap disajikan',
    ],
    imagePoster: 'https://i.ytimg.com/vi/kfNwgRuOelQ/maxresdefault.jpg',
    imageUrls: [
      'https://i.ytimg.com/vi/kfNwgRuOelQ/maxresdefault.jpg',
    ],
  ),
];